apiVersion: apps/v1
kind: Deployment 
metadata:
  name: portfolio-deploy
  labels:
    app: portfolio-app
  namespace: portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio-app
  template: 
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
      - name: portfolio
        image: namratha3/portfolio:v1
        ports:
        - containerPort: 80
