apiVersion: v1
kind: Service
metadata:
  name: portfolio-deploy
  namespace: portfolio
  labels:
    app: portfolio-app
spec:
  type: NodePort
  selector:
    app: portfolio-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
