apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio-app
  name: portfolio-deploy
  namespace: portfolio
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portfolio-app
  type: NodePort

